core/urls.py
# Django
from django.urls import path
# Core
from core.views import HomeView, remove_one_product_from_sale, add_one_product_to_sale, finish_sale

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('remove_one_product_from_sale/<pk>/', remove_one_product_from_sale, name='remove_one_product_from_sale'),
    path('add_one_product_to_sale/<pk>/', add_one_product_to_sale, name='add_one_product_to_sale'),
    path('finish_sale/<pk>/', finish_sale, name='finish_sale'),
]

django_store_admin/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
# Python
from decimal import Decimal
from django.contrib.messages.api import warning
# Django
from django.db import models
from django.utils.translation import gettext_lazy
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib import messages
from django.shortcuts import redirect

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name=gettext_lazy("name"))

    class Meta:
        verbose_name = gettext_lazy("category")
        verbose_name_plural = gettext_lazy("categories")

    def __str__(self) -> str:
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=255, verbose_name=gettext_lazy("name"))

    class Meta:
        verbose_name = gettext_lazy("brand")
        verbose_name_plural = gettext_lazy("brands")

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=gettext_lazy("category"))
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name=gettext_lazy("brand"))
    description = models.CharField(max_length=255, verbose_name=gettext_lazy("description"))
    presentation = models.CharField(max_length=255, verbose_name=gettext_lazy("presentation"))
    barcode = models.CharField(max_length=128, verbose_name=gettext_lazy("barcode"))

    @property
    def name(self):
        return f"{self.category.name} {self.brand.name} {self.description} {self.presentation}"

    @property
    def stock(self):
        try:
            lots = Lot.objects.filter(product=self).all()
            stock = 0
            for lot in lots:
                stock += lot.quantity
        except Lot.DoesNotExist:
            stock = 0
        return stock

    @property
    def investment(self):
        lots = Lot.objects.filter(product=self).all()
        amount_invested = 0
        for lot in lots:
            amount_invested_per_lot = lot.quantity * lot.unit_purchase_price
            amount_invested += amount_invested_per_lot
        return amount_invested

    def __str__(self) -> str:
        return self.name


class SellingPrice(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, verbose_name=gettext_lazy("product"))
    unit_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=gettext_lazy("unit price"))

    class Meta:
        verbose_name = gettext_lazy("selling price")
        verbose_name_plural = gettext_lazy("selling prices")

    def __str__(self):
        return f"Selling price of {self.product.name}"


class Lot(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=gettext_lazy("product"))
    quantity = models.PositiveIntegerField(default=1, verbose_name=gettext_lazy("quantity"))
    unit_purchase_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=gettext_lazy("unit purchase price"))
    package_purchase_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=gettext_lazy("package purchase price"))
    units_per_package = models.PositiveIntegerField(default=1, verbose_name=gettext_lazy("units per package"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=gettext_lazy("created at"))

    class Meta:
        verbose_name = gettext_lazy("lot")
        verbose_name_plural = gettext_lazy("lots")
        get_latest_by = "created_at"

    def __str__(self):
        return f"Lot of {self.product.name} registered at {self.created_at}"


class SaleProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=gettext_lazy("product"))
    unit_purchase_price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0, verbose_name=gettext_lazy("unit purchase price"))
    unit_selling_price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0, verbose_name=gettext_lazy("unit selling price"))
    sold = models.BooleanField(default=False, verbose_name=gettext_lazy("sold"))
    quantity = models.PositiveIntegerField(default=1, verbose_name=gettext_lazy("quantity"))

    @property
    def accumulated_purchase_price(self):
        accumulated_purchase_price = self.quantity * self.unit_purchase_price

    @property
    def accumulated_price(self):
        accumulated_price = self.quantity * self.unit_selling_price
        return accumulated_price

    class Meta:        
        verbose_name = gettext_lazy("sale product")
        verbose_name_plural = gettext_lazy("sale products")

    def __str__(self):
        return f"Product: {self.product.name} Quantity: {self.quantity}" 


class Sale(models.Model):
    products = models.ManyToManyField(SaleProduct, verbose_name=gettext_lazy("products"))
    sold = models.BooleanField(default=False, verbose_name=gettext_lazy("sold"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=gettext_lazy("created at"))
    sold_at = models.DateTimeField(null=True, verbose_name=gettext_lazy("sold at"))
    income = models.DecimalField(max_digits=8, decimal_places=2, default=0.0, verbose_name=gettext_lazy("income"))
    gross_profit = models.DecimalField(max_digits=8, decimal_places=2, default=0.0, verbose_name=gettext_lazy("gross profit"))

    @property
    def total_price(self):
        total_price = Decimal(0.0)
        for sale_product in self.products.all():
            total_price += sale_product.accumulated_price
        return total_price

    class Meta:
        verbose_name = gettext_lazy("sale")
        verbose_name_plural = gettext_lazy("sales")

    def __str__(self):
        return f"{self.created_at}"


class Scan(models.Model):
    barcode = models.CharField(max_length=128, verbose_name=gettext_lazy("barcode"))

    class Meta:
        verbose_name = gettext_lazy("scan")
        verbose_name_plural = gettext_lazy("scans")

    def __str__(self):
        return self.barcode

# TODO: Replace console prints with messages or something else

@receiver(post_save, sender=Scan)
def create_sale(instance, **kwargs):
    scan = instance
    barcode = scan.barcode

    if Product.objects.filter(barcode=barcode).exists():
        product = Product.objects.filter(barcode=barcode).get()
        if Lot.objects.filter(product=product).exists():
            earliest_lot = Lot.objects.filter(product=product).earliest()
            lots_of_product = Lot.objects.filter(product=product).all()
            product_stock = 0
            for lot in lots_of_product:
                product_stock += lot.quantity
            if SellingPrice.objects.filter(product=product).exists():

                if product_stock >= 0:
                    if Sale.objects.filter(sold=False).exists():
                        sale = Sale.objects.filter(sold=False).get()
                        if SaleProduct.objects.filter(product=product, sold=False).exists():
                            sale_product = SaleProduct.objects.filter(product__barcode=product.barcode, sold=False).get()
                            if sale_product.quantity >= product_stock:
                                print("There are no products in stock.")
                            else:
                                sale_product.quantity += 1
                                sale_product.save()
                                print("The product quantity has been updated!")
                        else:
                            if SellingPrice.objects.filter(product=product).exists():
                                selling_price = SellingPrice.objects.filter(product=product).get()
                                sale_product = SaleProduct.objects.create(
                                    product=product,
                                    unit_purchase_price=earliest_lot.unit_purchase_price,
                                    unit_selling_price=selling_price.unit_price
                                )
                                sale.products.add(sale_product)
                                print("Product added!")
                            else:
                                print("The product does not have a selling price.")
                    else:
                        if SellingPrice.objects.filter(product=product).exists():
                            selling_price = SellingPrice.objects.filter(product=product).get()
                            sale_product = SaleProduct.objects.create(
                                product=product,
                                unit_purchase_price=earliest_lot.unit_purchase_price,
                                unit_selling_price=selling_price.unit_price
                            )
                            sale = Sale.objects.create()
                            sale.products.add(sale_product)
                            print("Product added!")
                        else:
                            print("The product does not have a selling price.")
                else:
                    print("This product is out of stock.")
                
            else:
                print("The product does not have a selling price.")
        else:
            print("This product is out of stock.")
    else:
        print("This product doesn't exist.")

core/forms.py
# Django
from django import forms

class BarcodeForm(forms.Form):
    barcode = forms.CharField(
        max_length=128,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escanear código de barras',
                'class': 'form-control',
                'aria-describedby': 'button-addon2',
                'autofocus': 'True',
                'autocomplete': 'off'
            }
        )
    )

core/views.py
# Python
from decimal import Decimal
# Django
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Core
from core.models import Category, Brand, Product, SellingPrice, Lot, SaleProduct, Sale, Scan
from core.forms import BarcodeForm

# Create your views here.

class HomeView(TemplateView):
    def get(self, *args, **kwargs):
        form = BarcodeForm()
        try:
            sale = Sale.objects.filter(sold=False).get()
            context = {
                'form': form,
                'sale': sale,
            }
        except Sale.DoesNotExist:
            # messages.error(self.request, "No hay una venta activa!")
            context = {
                'form': form,
            }
        return render(self.request, 'home.html', context)

    def post(self, request, *args, **kwargs):
        form = BarcodeForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data.get('barcode')
            scan = Scan.objects.create(barcode=barcode)
        # HttpResponseRedirect clear POST data.
        return HttpResponseRedirect(request.path)

@login_required
def add_one_product_to_sale(request, pk):
    product = Product.objects.filter(pk=pk).get()
    if Sale.objects.filter(sold=False).exists():
        sale = Sale.objects.filter(sold=False).get()
        try:
            sale_product = SaleProduct.objects.get(product=product, sold=False)
            lots_of_product = Lot.objects.filter(product=product).all()
            product_stock = 0
            for lot in lots_of_product:
                product_stock += lot.quantity
                
            if sale_product.quantity >= product_stock:
                messages.warning(request, "Ya no quedan productos en stock, no puede agregar mas.")
            else:
                sale_product.quantity += 1
                sale_product.save()
                messages.info(request, "La cantidad de producto se modifico exitosamente!")
            return redirect("core:home")
        except SaleProduct.DoesNotExist:
            messages.info(request, "Este producto no estaba en la venta!")
            return redirect("core:home")
    else:
        return redirect("core:home")

@login_required
def remove_one_product_from_sale(request, pk):
    product = Product.objects.filter(pk=pk).get()
    if Sale.objects.filter(sold=False).exists():
        sale = Sale.objects.filter(sold=False).get()
        try:
            sale_product = SaleProduct.objects.get(product=product, sold=False)
            if sale_product.quantity <= 1:
                sale_product.delete()
                if sale.products.exists() == False:
                    sale.delete()
                messages.info(request, "Venta eliminada.")
            else:
                sale_product.quantity -= 1
                sale_product.save()
                messages.info(request, "La cantidad de producto se modifico exitosamente!")
            return redirect("core:home")
        except SaleProduct.DoesNotExist:
            messages.danger(request, "Este producto no estaba en la venta!")
            return redirect("core:home")
    else:
        return redirect("core:home")

@login_required
def finish_sale(request, pk):
    sale = Sale.objects.get(pk=pk)
    total_cost = Decimal(0.0)
    total_price = Decimal(0.0)
    for sale_product in sale.products.all():
        product = sale_product.product
        earliest_lot = Lot.objects.filter(product=product).earliest()
        if earliest_lot.quantity == sale_product.quantity:
            earliest_lot.delete()
        else:
            if earliest_lot.quantity >= sale_product.quantity:
                earliest_lot.quantity -= sale_product.quantity
                earliest_lot.save()
            else:
                missing_products = sale_product.quantity - earliest_lot.quantity
                next_lot = Lot.objects.filter(product=product).order_by('created_at')[1]
                next_lot.quantity -= missing_products
                next_lot.save()
                earliest_lot.delete()
        accumulated_purchase_price = sale_product.quantity * sale_product.unit_purchase_price
        total_cost += accumulated_purchase_price
        accumulated_selling_price = sale_product.quantity * sale_product.unit_selling_price
        total_price += accumulated_selling_price
        sale_product.sold = True
        sale_product.save()
    sale.sold = True
    sale.sold_at = timezone.now()
    sale.income = total_price
    sale.gross_profit = sale.total_price - total_cost
    sale.save()
    scans = Scan.objects.all()
    scans.delete()
    messages.success(request, 'Venta finalizada!')
    return redirect("core:home")

core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/f15858b618.js" crossorigin="anonymous"></script>

    <title>Abarrotes del Centro</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:home' %}">Abarrotes del Centro</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'core:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container mt-3">
        {% if request.user.is_authenticated %}
            {% block messages %}
                {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message|capfirst }}</div>
                    {% endfor %}
                {% endif %}
            {% endblock messages %}
            {% block content %}
            {% endblock %}
        {% endif %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

core/templates/home.html
{% extends "base.html" %}

{% block content %}
    <form action="{% url 'core:home' %}" method="POST">
        {% csrf_token %}
        <div class="input-group mb-3">
            {{ form.barcode }}
            <!--<input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">-->
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Agragar</button>
        </div>
    </form>
    {% if sale %}
    <h1>Venta</h1>
    <ul class="list-group">
        <li class="list-group-item active">
            <div class="row">
                <div class="col-6">Producto</div>
                <div class="col-3">Cantidad</div>
                <div class="col-3">Precio</div>
            </div>
        </li>
        {% for sale_product in sale.products.all %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-6">
                    {{ sale_product.product.name }}
                </div>
                <div class="col-3">
                    <a class="" href="{% url 'core:remove_one_product_from_sale' sale_product.product.pk %}"><i class="fas fa-minus-circle"></i></a>
                    {{ sale_product.quantity }}
                    <a class="" href="{% url 'core:add_one_product_to_sale' sale_product.product.pk %}"><i class="fas fa-plus-circle"></i></a>
                </div>
                <div class="col-3">${{ sale_product.accumulated_price }}</div>
            </div>
        </li>
        {% endfor %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-9">
                    <h4>Total:</h4>
                </div>
                <div class="col-3">
                    <h2>${{ sale.total_price }}</h2>
                </div>
            </div>
        </li>
    </ul>
    <div class="row mt-3">
        <a href="{% url 'core:finish_sale' sale.pk %}" class="btn btn-success btn-block">Finalizar Venta</a>
    </div>
    {% else %}
    <h1>No hay ventas activas.</h1>
    {% endif %}
{% endblock content %}